/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ApiDataIndexImport } from './routes/api-data/index'
import { Route as GlobalStatePath2Import } from './routes/global-state/path2'
import { Route as GlobalStatePath1Import } from './routes/global-state/path1'
import { Route as ApiDataItemIdImport } from './routes/api-data/$itemId'

// Create Virtual Routes

const FormLazyImport = createFileRoute('/form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const FormLazyRoute = FormLazyImport.update({
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ApiDataIndexRoute = ApiDataIndexImport.update({
  path: '/api-data/',
  getParentRoute: () => rootRoute,
} as any)

const GlobalStatePath2Route = GlobalStatePath2Import.update({
  path: '/global-state/path2',
  getParentRoute: () => rootRoute,
} as any)

const GlobalStatePath1Route = GlobalStatePath1Import.update({
  path: '/global-state/path1',
  getParentRoute: () => rootRoute,
} as any)

const ApiDataItemIdRoute = ApiDataItemIdImport.update({
  path: '/api-data/$itemId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/api-data/$itemId': {
      preLoaderRoute: typeof ApiDataItemIdImport
      parentRoute: typeof rootRoute
    }
    '/global-state/path1': {
      preLoaderRoute: typeof GlobalStatePath1Import
      parentRoute: typeof rootRoute
    }
    '/global-state/path2': {
      preLoaderRoute: typeof GlobalStatePath2Import
      parentRoute: typeof rootRoute
    }
    '/api-data/': {
      preLoaderRoute: typeof ApiDataIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  FormLazyRoute,
  ApiDataItemIdRoute,
  GlobalStatePath1Route,
  GlobalStatePath2Route,
  ApiDataIndexRoute,
])

/* prettier-ignore-end */
